[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[nixpacks]
providers = ["node"]

[deploy]
startCommand = "npm run preview -- --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NIXPACKS_NODE_VERSION = "20"
