[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev --no-audit --no-fund && npm run build"

[nixpacks]
providers = ["node"]

[deploy]
startCommand = "npx serve -s dist -l $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
NIXPACKS_NODE_VERSION = "20"
NPM_CONFIG_PRODUCTION = "false"
